---
- name: Install add-apt-repostory
  apt:
    name: software-properties-common 
    state: latest

- name: Add Oracle Java Repository
  apt_repository: 
    repo: 'ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java 8
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Create java home
  shell: echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | sudo tee -a /etc/environment
- name: source  the file
  shell: source /etc/environment
  args:
    executable: /bin/bash